[package]
name = "bropt"
version = "0.1.0"
edition = "2024"

[lib]
name = "bropt"
crate-type = ["rlib", "cdylib"]

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
